version: '3'

services:
  app:
    environment:
      - AUTH=SAML_MOCK
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./retention_dashboard:/app/retention_dashboard
    ports:
      - "8000:8000"
  devtools:
    restart: always
    container_name: devtools
    image: node:8.16.0-jessie
    volumes:
      - ./package.json:/devtools/retention_dashboard/package.json
      - ./webpack.config.js:/devtools/retention_dashboard/webpack.config.js
      - ./retention_dashboard:/devtools/retention_dashboard/retention_dashboard
    working_dir: /devtools/retention_dashboard
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
