version: '3'

services:
  app:
    environment:
      - AUTH=SAML_MOCK
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./retention_dashboard:/app/retention_dashboard
    ports:
      - "8000:8000"
  devtools:
    restart: always
    container_name: devtools
    image: node:8.16.0-jessie
    volumes:
#      - ./package.json:/devtools/cohort-manager/package.json
#      - ./webpack.config.js:/devtools/cohort-manager/webpack.config.js
      - ./retention_dashboard:/devtools/cohort-manager/retention_dashboard
    working_dir: /devtools/retention_dashboard
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
