# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.12 on 2020-05-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')], default=1)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'OMAD'), (2, 'EOP'), (3, 'International')])),
                ('uploaded_by', models.CharField(max_length=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retention_dashboard.Week')),
            ],
            options={
                'unique_together': {('type', 'week')},
            },
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'OMAD'), (2, 'EOP'), (3, 'International')])),
                ('student_name', models.TextField()),
                ('student_number', models.IntegerField()),
                ('netid', models.CharField(max_length=12)),
                ('premajor', models.BooleanField()),
                ('priority_score', models.FloatField()),
                ('activity_score', models.FloatField()),
                ('assignment_score', models.FloatField()),
                ('grade_score', models.FloatField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retention_dashboard.Upload')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='retention_dashboard.Week')),
            ],
        ),
    ]
