# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.12 on 2020-05-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International')]),
        ),
    ]
