# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.12 on 2020-05-20 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0002_auto_20200514_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.TextField()),
                ('advisor_netid', models.CharField(max_length=12)),
                ('advisor_type', models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International')])),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='retention_dashboard.Advisor'),
        ),
    ]
