# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.2.12 on 2020-10-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0005_auto_20200706_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='is_freshman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='is_stem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='signin_score',
            field=models.FloatField(default=0.0),
        ),
    ]
