# Generated by Django 2.2.19 on 2021-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0007_auto_20210225_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma')]),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma')]),
        ),
    ]
