# Generated by Django 2.2.19 on 2021-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0008_auto_20210621_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='activity_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='assignment_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='grade_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='priority_score',
            field=models.FloatField(null=True),
        ),
    ]
