# Generated by Django 2.2.19 on 2021-12-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0010_auto_20211118_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='class_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='advisor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma'), (6, 'Athletic')]),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma'), (6, 'Athletic')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma'), (6, 'Athletic')]),
        ),
    ]
