# Generated by Django 2.2.19 on 2021-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0012_auto_20211208_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='campus_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='eop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='iss',
            field=models.BooleanField(default=False),
        ),
    ]
