# Generated by Django 2.2.19 on 2021-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0013_auto_20211210_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='is_freshman',
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='sports',
            field=models.ManyToManyField(to='retention_dashboard.Sport'),
        ),
    ]
