# Generated by Django 2.2.19 on 2022-03-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_dashboard', '0014_auto_20211223_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='engineering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='advisor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma'), (6, 'Athletics'), (7, 'Engineering')]),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma'), (6, 'Athletics'), (7, 'Engineering')]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Premajor'), (2, 'EOP'), (3, 'International'), (4, 'ISS'), (5, 'Tacoma'), (6, 'Athletics'), (7, 'Engineering')]),
        ),
    ]
