ingress:
  enabled: true
  tls:
    retention-dashboard:
      secretName: test.retention.uw.edu-ingress-cert
      hosts:
        - test.retention.uw.edu
  hosts:
    retention-dashboard:
      host: test.retention.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
database:
  engine: postgres
  secretName: test.retention.uw.edu-sql-secrets
  hostname: retention-db
  name: retention-test
gcsCredentials:
  mounted: true
  secretName: test.retention.uw.edu-gcs-credentials
cronjob:
  enabled: true
  jobs:
    - name: auto-load-rad
      schedule: "0 14 * * 0" # At 7:00am PDT on Sunday
      command: ["/scripts/management_command.sh"]
      args: ["upload_file"]
externalService:
  enabled: true
  name: retention-db
  type: ClusterIP
  serviceAddress: 172.18.1.39
  servicePort: 5432
externalSecrets:
  enabled: true
  secrets:
    - name: test.retention.uw.edu-secrets
      externalKey: axdd/kv/data/retention/test/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: storage-bucket-name
          property: storage-bucket-name
        - name: ga-key
          property: ga-key
    - name: test.retention.uw.edu-shared-secrets
      externalKey: axdd/kv/data/retention/shared/secrets
        - name: storage-project-id
          property: storage-project-id
    - name: test.retention.uw.edu-sql-secrets
      externalKey: axdd/kv/data/retention/test/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: test.retention.uw.edu-uwca-certs
      externalKey: axdd/kv/data/retention/test/uwca-certs
      data:
        - name: test.retention.uw.edu-uwca.cert
          property: test.retention.uw.edu-uwca.cert
        - name: test.retention.uw.edu-uwca.key
          property: test.retention.uw.edu-uwca.key
    - name: test.retention.uw.edu-ic-certs
      externalKey: axdd/kv/data/retention/test/ic-certs
      data:
        - name: test.retention.uw.edu-ic.cert
          property: test.retention.uw.edu-ic.cert
    - name: test.retention.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert
    - name: test.retention.uw.edu-gcs-credentials
      externalKey: axdd/kv/data/retention/shared/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
repo: retention-dashboard
instance: test
branch: develop
certs:
  mounted: true
  certPath: /certs/test.retention.uw.edu-uwca.cert
  keyPath: /certs/test.retention.uw.edu-uwca.key
  secretName: test.retention.uw.edu-uwca-certs
image:
  repository: gcr.io/uwit-mci-axdd/retention-dashboard
  tag: IMAGE_TAG
environmentVariables:
  - name: ENV
    value: eval
  - name: AUTH
    value: SAML
  - name: CLUSTER_CNAME
    value: test.retention.uw.edu
environmentVariablesSecrets:
  gaKey:
    name: GA_KEY
    secretName: test.retention.uw.edu-secrets
    secretKey: ga-key
  djangoSecret:
    name: DJANGO_SECRET
    secretName: test.retention.uw.edu-secrets
    secretKey: django-secret
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: test.retention.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: test.retention.uw.edu-shared-secrets
    secretKey: storage-project-id
  samlSPCert:
  samlSPCert:
    name: SP_CERT
    secretName: test.retention.uw.edu-ic-certs
    secretKey: test.retention.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: test.retention.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
