ingress:
  enabled: true
  type: nginx
  tls:
    prereq:
      secretName: aat-test.axdd.s.uw.edu
      hosts:
        - aat-test.axdd.s.uw.edu
  hosts:
    prereq:
      host: aat-test.axdd.s.uw.edu
      paths:
        - "/"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
database:
  engine: postgres
  secretName: aat-db-test-credentials
  hostname: aat-db-test
  name: aat-db-test
externalService:
  enabled: true
  name: aat-db-test
  type: ClusterIP
  serviceAddress: 172.18.1.20
  servicePort: 5432
repo: admissions-cohort-manager
instance: test
branch: develop
certs:
  mounted: true
  certPath: /certs/tls.crt
  keyPath: /certs/tls.key
  secretName: aat-uwca
environmentVariables:
  - name: AUTH
    value: SAML
  - name: ADSEL_ENV
    value: EVAL
image:
  repository: registry.hub.docker.com/acait/aat
  tag: IMAGE_TAG
environmentVariables:
  - name: ENV
    value: eval
  - name: AUTH
    value: SAML
  - name: CLUSTER_CNAME
    value: aat-test.axdd.s.uw.edu
  - name: SP_CERT
    value: 'MIIHADCCBeigAwIBAgIQDIJv3ghvAbmJsANrd3mD9zANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBBcmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjEfMB0GA1UEAxMWSW5Db21tb24gUlNBIFNlcnZlciBDQTAeFw0xOTExMjYwMDAwMDBaFw0yMTExMjUyMzU5NTlaMIGzMQswCQYDVQQGEwJVUzEOMAwGA1UEERMFOTgxOTUxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1NlYXR0bGUxGTAXBgNVBAkTEDQ1NDUgMTV0aCBBdmUgTkUxITAfBgNVBAoTGFVuaXZlcnNpdHkgb2YgV2FzaGluZ3RvbjEOMAwGA1UECxMFVVctSVQxHzAdBgNVBAMTFmFhdC10ZXN0LmF4ZGQucy51dy5lZHUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDPkclwAOmv1SgSv6ATHjzlA9hIPW6qiPiBApgvHRQTmeOb5Vx0rvPr0TBBjbpjxwv00XS4LgPCV2wMaaaJxw0i0AVI+xjV6DPPI9UeHR7CwvzaLk7w0ri9zlKK81PXYq/O0cv/A3uGjW6xDzBGD2FLIrUimjrtDgblTy12Xz5WOYlVOOOK2OVQ7nFrANMgar32nSsWZK1Q6JnBi6K+KXT9G63cY2plrupcxviIR97eCo6oC0T4IfsJPR+lJAd5O9o2Xbu+R516pCfPsOCt72zUWAtUelnwLjG8kJ6MaXVV89C/G6z9oNNheTknXmPI/iBDufm5TUONZ0IMqskNu+XDAgMBAAGjggNKMIIDRjAfBgNVHSMEGDAWgBQeBaN3j2yW4luHS6a0hqxxAAznODAdBgNVHQ4EFgQUi8j6MwVbc4ImWqP5mxTMmzJOyeIwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMGcGA1UdIARgMF4wUgYMKwYBBAGuIwEEAwEBMEIwQAYIKwYBBQUHAgEWNGh0dHBzOi8vd3d3LmluY29tbW9uLm9yZy9jZXJ0L3JlcG9zaXRvcnkvY3BzX3NzbC5wZGYwCAYGZ4EMAQICMEQGA1UdHwQ9MDswOaA3oDWGM2h0dHA6Ly9jcmwuaW5jb21tb24tcnNhLm9yZy9JbkNvbW1vblJTQVNlcnZlckNBLmNybDB1BggrBgEFBQcBAQRpMGcwPgYIKwYBBQUHMAKGMmh0dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9JbkNvbW1vblJTQVNlcnZlckNBXzIuY3J0MCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMCEGA1UdEQQaMBiCFmFhdC10ZXN0LmF4ZGQucy51dy5lZHUwggF8BgorBgEEAdZ5AgQCBIIBbASCAWgBZgB2AH0+8viP/4hVaCTCwMqeUol5K8UOeAl/LmqXaJl+IvDXAAABbqV8NpgAAAQDAEcwRQIhAIJ5bugfoAnRL33KQZqU8cUNaYtbVpbbOykfCpLZpPiDAiA0sc0/RE0zBCJlLVdsxeO65f66n/YAiaTKiUyhVJLMmQB1AESUZS6w7s6vxEAH2Kj+KMDa5oK+2MsxtT/TM5a1toGoAAABbqV8NoEAAAQDAEYwRAIgAwdf3yGXc8Aw7BFtIccF2h777RG3w58XWWWsfMxgaNMCIHfpeL/hiGv4cNA9T6f1UsiHLEASfv35L4+lfQIDI+HzAHUAb1N2rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAFupXw2iAAABAMARjBEAiALN/bAysz+9uVyxmouwOSDi43g3fhb2RznWlQzqf/fWwIgHUJ06iz/ANlkorxr91OhIakG9OwGhf/lpk9dq506hcMwDQYJKoZIhvcNAQELBQADggEBADuLjn9ZO2unATArio8WalHktc+4NoY6k4bPhC+iYVTTrjghW0ANA0Q+Hi7FIayJxAKIr86OrD68VIX2FVRK7Pm2K0pDuSWzLWjYZQhG0Ch2MRVSPvBZCocwkRcn+7xqZd8hZ4tzwRt6xuynE1tqkDBBNdbjkVQCAf81nCNefhnKe9BuRXZObtMAVVWz6jO1Ft1VDY7Lm6+WM0pvhxYBiQgC38TO4FufWwIB2dIcepbT9ke5MmfWI7pH3Hn9nSxFmB1siKk7+OGVuw9qyIjLxYcsl41RFmDPYJN7Aiq0Yn1uKV2R1+W2X++RlptL6xN1U0wgnXxCktVnmTCu3SAJAA8='
  - name: IDP_CERT
    value: 'MIID/TCCAuWgAwIBAgIJAMoYJbDt9lKKMA0GCSqGSIb3DQEBBQUAMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTAeFw0xMTA0MjYxOTEwMzlaFw0yMTA0MjMxOTEwMzlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMH9G8m68L0Hf9bmf4/7c+ERxgDQrbq50NfSi2YTQWc1veUIPYbZy1agSNuc4dwn3RtC0uOQbdNTYUAiVTcYgaYceJVB7syWf9QyGIrglZPMu98c5hWb7vqwvs6d3s2Sm7tBib2v6xQDDiZ4KJxpdAvsoPQlmGdgpFfmAsiYrnYFXLTHgbgCc/YhV8lubTakUdI3bMYWfh9dkj+DVGUmt2gLtQUzbuH8EU44vnXgrQYSXNQkmRcyoE3rj4Rhhbu/p5D3P+nuOukLYFOLRaNeiiGyTu3P7gtc/dy/UjUrf+pH75UUU7Lb369dGEfZwvVtITXsdyp0pBfun4CP808H9N0CAwEAAaOBwTCBvjAdBgNVHQ4EFgQUP5smx3ZYKODMkDglkTbduvLcGYAwgY4GA1UdIwSBhjCBg4AUP5smx3ZYKODMkDglkTbduvLcGYChYKReMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJXQTEhMB8GA1UEChMYVW5pdmVyc2l0eSBvZiBXYXNoaW5ndG9uMR0wGwYDVQQDExRpZHAudS53YXNoaW5ndG9uLmVkdYIJAMoYJbDt9lKKMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAEo7c2CNHEI+Fvz5DhwumU+WHXqwSOK47MxXwNJVpFQ9GPR2ZGDAq6hzLJLAVWcY4kB3ECDkRtysAWSFHm1roOU7xsU9f0C17QokoXfLNC0d7KoivPM6ctl8aRftU5moyFJkkJX3qSExXrl053uxTOQVPms4ypkYv1A/FBZWgSC8eNoYnBnv1Mhy4m8bfeEN7qT9rFoxh4cVjMH1Ykq7JWyFXLEB4ifzH4KHyplt5Ryv61eh6J1YPFa2RurVTyGpHJZeOLUIBvJu15GzcexuDDXe0kg7sHD6PbK0xzEF/QeXP/hXzMxR9kQXB/IR/b2k4ien+EM3eY/ueBcTZ95dgVM='

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: aat-test-django-secret
    secretKey: django-secret
